site_name: "Ngkolmpu verbal paradigms"
docs_dir: docs
theme:
  palette:
    primary: red
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
plugins:
  - paralex:
      paralex_package_path: "ngkolmpu.package.json"
      layout_tables:
        - tense
        - aspect
        - mood
      layout_rows:
        - undergoer person
        - undergoer number
        - gender
      layout_columns:
        - actor person
        - actor number
        - pluractionality
repo_url: https://github.com/maecarroll/Ngkolmpu-Paralex
